#! /bin/bash

set -e
set -x

JAVA_INSTALL_VERSION_MAJOR='8'
JAVA_INSTALL_VERSION=181
MAGIC_B_NUM=13
JAVA_INSTALL_LINK_HASH=96a7b8442fe848ef90c96a2fad6ed6d1
JAVA_INSTALL_PATH=/usr/opt/java-8-${JAVA_INSTALL_VERSION}/
DOWNLOAD_URL=http://download.oracle.com/otn-pub/java/jdk/8u${JAVA_INSTALL_VERSION}-b${MAGIC_B_NUM}/${JAVA_INSTALL_LINK_HASH}/jdk-8u${JAVA_INSTALL_VERSION}-linux-x64.tar.gz
echo "Installing Java 8u${JAVA_INSTALL_VERSION} to ${JAVA_INSTALL_PATH}"

mkdir -p ${JAVA_INSTALL_PATH}
cd ${JAVA_INSTALL_PATH}

curl -j -k -L -H "Cookie: oraclelicense=accept-securebackup-cookie" \
  http://download.oracle.com/otn-pub/java/jdk/8u${JAVA_INSTALL_VERSION}-b${MAGIC_B_NUM}/${JAVA_INSTALL_LINK_HASH}/jdk-8u${JAVA_INSTALL_VERSION}-linux-x64.tar.gz > jdk-8u${JAVA_INSTALL_VERSION}-linux-x64.tar.gz

tar zxvf jdk-8u${JAVA_INSTALL_VERSION}-linux-x64.tar.gz
rm jdk-8u${JAVA_INSTALL_VERSION}-linux-x64.tar.gz

cd jdk*
mkdir -p /usr/lib/jvm/
echo "Symlinking /usr/lib/jvm/java-8-oracle/ -> $(pwd)"
ln -s -f $(pwd) /usr/lib/jvm/java-8-oracle
